### ISSUE TITLE
How to query?

### ISSUE THREAD

**Issue by fishuke** [questdb/nodejs-questdb-client#10]
I see there is sender implementation but where is reading?

**Comment by fahminlb33** [comment]
I'm also looking for query support in this library. For now I think the only possible ways to query data from QuestDB is from REST API or PostgreSQL wire protocol. It would be really helpful to also include querying capability to this library so I don't have to use `pg`

**Comment by fishuke** [comment]
I also used pg for reading hopefully it will be integrated.

**Comment by fahminlb33** [comment]
Based on the [documentation](https://questdb.io/docs/develop/connect/) this library looks like uses the InfluxDB Line Protocol which doesn't support querying data (the example uses port 9009).

**Comment by glasstiger** [comment]
Sorry but missed this question somehow.
You are correct, the client uses ILP to ingest data into QuestDB and does not support queries.
You can use the REST API or Postgres wire protocol to query the data.
There are plans to add support for queries through the client but not sure when it will be implemented.

**Comment by teddybee** [comment]
I have run into this issue. It would be nice to somehow the client could send queries to the db with the same connection config as the sender.
