### ISSUE TITLE
Missing method to insert binary data

### ISSUE THREAD

**Issue by fritzdimmel** [questdb/nodejs-questdb-client#19]
Hi,
in the QuestDB spec there's a column type "binary".
We want to use this column type to store base64 encoded data.
Unfortunately, there's no "binaryColumn" method in sender.js. 
Is this planned or is there any other way to insert binary data using this library?
Thanks

**Comment by glasstiger** [comment]
Hi, I am probably very late to the party, but the short answer is: no.
QuestDB clients use ILP (InfluxDB Line Protocol) under the hood, and this protocol is text based.
But if your data is already base64 encoded you could just create a STRING column in QuestDB, and ingest the binary data in base64 encoded format.
Of course, when you query the table you will need to decode it back to binary.

**Comment by glasstiger** [comment]
There are plans to change QuestDB clients to use binary protocol, and ditch ILP.
When that happens we should be able to add a "binaryColumn()" method to all clients.

**Comment by fritzdimmel** [comment]
Hi, thanks for letting me know. Looking forward to some "native" implementation in the future. Until then, we'll stick with encode/decode wrappers.
Thanks
